#------------------------------------
# Spring settings
#------------------------------------

spring:
  application:
    name: bh-management

  # Datasource settings
  datasource:
    url: jdbc:postgresql://localhost:5432/bh_management
    username: root
    password: adminadmin
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      pool-name: bhm-pool

  # Flyway settings
  flyway:
    enabled: true
    locations: classpath:schema
    validate-on-migrate: true
    mixed: true
    out-of-order: true
    table: schema_version

#------------------------------------
# Server settings
#------------------------------------

server:
  port: 9000
  servlet:
    context-path: /api